[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "SciGlassPlus"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE.txt" }